DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    WHERE t.typname = 'CommercialStatus'
      AND e.enumlabel = 'PARTIALLY_SOLD'
  ) THEN
    ALTER TYPE "CommercialStatus" ADD VALUE 'PARTIALLY_SOLD' AFTER 'OPEN';
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'ClientPersonType'
  ) THEN
    CREATE TYPE "ClientPersonType" AS ENUM ('PF', 'PJ');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'ClientStatus'
  ) THEN
    CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'INACTIVE');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'ClientRegistrationStatus'
  ) THEN
    CREATE TYPE "ClientRegistrationStatus" AS ENUM ('ACTIVE', 'INACTIVE');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'SampleMovementType'
  ) THEN
    CREATE TYPE "SampleMovementType" AS ENUM ('SALE', 'LOSS');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'SampleMovementStatus'
  ) THEN
    CREATE TYPE "SampleMovementStatus" AS ENUM ('ACTIVE', 'CANCELLED');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'ClientAuditEventType'
  ) THEN
    CREATE TYPE "ClientAuditEventType" AS ENUM (
      'CLIENT_CREATED',
      'CLIENT_UPDATED',
      'CLIENT_INACTIVATED',
      'CLIENT_REACTIVATED',
      'CLIENT_REGISTRATION_CREATED',
      'CLIENT_REGISTRATION_UPDATED',
      'CLIENT_REGISTRATION_INACTIVATED',
      'CLIENT_REGISTRATION_REACTIVATED'
    );
  END IF;
END
$$;

CREATE TABLE "client" (
  "id" UUID NOT NULL,
  "code" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "person_type" "ClientPersonType" NOT NULL,
  "full_name" TEXT,
  "legal_name" TEXT,
  "trade_name" TEXT,
  "cpf" TEXT,
  "cnpj" TEXT,
  "document_canonical" TEXT NOT NULL,
  "phone" TEXT,
  "is_buyer" BOOLEAN NOT NULL DEFAULT FALSE,
  "is_seller" BOOLEAN NOT NULL DEFAULT FALSE,
  "status" "ClientStatus" NOT NULL DEFAULT 'ACTIVE',
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "client_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_client_code" UNIQUE ("code"),
  CONSTRAINT "uq_client_document_canonical" UNIQUE ("document_canonical"),
  CONSTRAINT "chk_client_role_flags" CHECK ("is_buyer" OR "is_seller"),
  CONSTRAINT "chk_client_document_canonical_non_blank" CHECK (btrim("document_canonical") <> ''),
  CONSTRAINT "chk_client_person_type_fields" CHECK (
    (
      "person_type" = 'PF'
      AND "full_name" IS NOT NULL
      AND btrim("full_name") <> ''
      AND "cpf" IS NOT NULL
      AND btrim("cpf") <> ''
      AND "legal_name" IS NULL
      AND "trade_name" IS NULL
      AND "cnpj" IS NULL
    )
    OR
    (
      "person_type" = 'PJ'
      AND "legal_name" IS NOT NULL
      AND btrim("legal_name") <> ''
      AND "cnpj" IS NOT NULL
      AND btrim("cnpj") <> ''
      AND "full_name" IS NULL
      AND "cpf" IS NULL
    )
  )
);

CREATE TABLE "client_registration" (
  "id" UUID NOT NULL,
  "client_id" UUID NOT NULL,
  "status" "ClientRegistrationStatus" NOT NULL DEFAULT 'ACTIVE',
  "registration_number" TEXT NOT NULL,
  "registration_number_canonical" TEXT NOT NULL,
  "registration_type" TEXT NOT NULL,
  "address_line" TEXT NOT NULL,
  "district" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "state" VARCHAR(2) NOT NULL,
  "postal_code" TEXT NOT NULL,
  "complement" TEXT,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "client_registration_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uq_client_registration_number_canonical" UNIQUE ("registration_number_canonical"),
  CONSTRAINT "uq_client_registration_id_client" UNIQUE ("id", "client_id"),
  CONSTRAINT "fk_client_registration_client"
    FOREIGN KEY ("client_id") REFERENCES "client"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "chk_client_registration_number_non_blank" CHECK (btrim("registration_number") <> ''),
  CONSTRAINT "chk_client_registration_number_canonical_non_blank" CHECK (btrim("registration_number_canonical") <> ''),
  CONSTRAINT "chk_client_registration_type_non_blank" CHECK (btrim("registration_type") <> ''),
  CONSTRAINT "chk_client_registration_address_non_blank" CHECK (btrim("address_line") <> ''),
  CONSTRAINT "chk_client_registration_district_non_blank" CHECK (btrim("district") <> ''),
  CONSTRAINT "chk_client_registration_city_non_blank" CHECK (btrim("city") <> ''),
  CONSTRAINT "chk_client_registration_state_valid" CHECK (char_length("state") = 2),
  CONSTRAINT "chk_client_registration_postal_code_non_blank" CHECK (btrim("postal_code") <> '')
);

CREATE TABLE "client_audit_event" (
  "event_id" UUID NOT NULL,
  "target_client_id" UUID,
  "target_registration_id" UUID,
  "actor_user_id" UUID,
  "event_type" "ClientAuditEventType" NOT NULL,
  "payload" JSONB NOT NULL,
  "reason_text" TEXT,
  "request_id" TEXT NOT NULL,
  "correlation_id" TEXT,
  "metadata_ip" TEXT,
  "metadata_user_agent" TEXT,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "client_audit_event_pkey" PRIMARY KEY ("event_id"),
  CONSTRAINT "fk_client_audit_target_client"
    FOREIGN KEY ("target_client_id") REFERENCES "client"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_client_audit_target_registration"
    FOREIGN KEY ("target_registration_id", "target_client_id") REFERENCES "client_registration"("id", "client_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_client_audit_actor_user"
    FOREIGN KEY ("actor_user_id") REFERENCES "app_user"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "chk_client_audit_target_registration_requires_client" CHECK (
    "target_registration_id" IS NULL OR "target_client_id" IS NOT NULL
  )
);

CREATE TABLE "sample_movement" (
  "id" UUID NOT NULL,
  "sample_id" UUID NOT NULL,
  "movement_type" "SampleMovementType" NOT NULL,
  "status" "SampleMovementStatus" NOT NULL DEFAULT 'ACTIVE',
  "buyer_client_id" UUID,
  "buyer_registration_id" UUID,
  "quantity_sacks" INTEGER NOT NULL,
  "movement_date" DATE NOT NULL,
  "notes" TEXT,
  "reason_text" TEXT,
  "buyer_client_snapshot" JSONB,
  "buyer_registration_snapshot" JSONB,
  "version" INTEGER NOT NULL DEFAULT 0,
  "cancelled_at" TIMESTAMPTZ(6),
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sample_movement_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk_sample_movement_sample"
    FOREIGN KEY ("sample_id") REFERENCES "sample"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_sample_movement_buyer_client"
    FOREIGN KEY ("buyer_client_id") REFERENCES "client"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_sample_movement_buyer_registration"
    FOREIGN KEY ("buyer_registration_id", "buyer_client_id") REFERENCES "client_registration"("id", "client_id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "chk_sample_movement_quantity_positive" CHECK ("quantity_sacks" >= 1),
  CONSTRAINT "chk_sample_movement_buyer_registration_requires_client" CHECK (
    "buyer_registration_id" IS NULL OR "buyer_client_id" IS NOT NULL
  ),
  CONSTRAINT "chk_sample_movement_type_fields" CHECK (
    (
      "movement_type" = 'SALE'
      AND "buyer_client_id" IS NOT NULL
    )
    OR
    (
      "movement_type" = 'LOSS'
      AND "buyer_client_id" IS NULL
    )
  ),
  CONSTRAINT "chk_sample_movement_cancelled_state" CHECK (
    ("status" = 'ACTIVE' AND "cancelled_at" IS NULL)
    OR
    ("status" = 'CANCELLED' AND "cancelled_at" IS NOT NULL)
  )
);

ALTER TABLE "sample"
  ADD COLUMN IF NOT EXISTS "owner_client_id" UUID,
  ADD COLUMN IF NOT EXISTS "owner_registration_id" UUID,
  ADD COLUMN IF NOT EXISTS "sold_sacks" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lost_sacks" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "sample"
  ADD CONSTRAINT "fk_sample_owner_client"
  FOREIGN KEY ("owner_client_id") REFERENCES "client"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "sample"
  ADD CONSTRAINT "fk_sample_owner_registration"
  FOREIGN KEY ("owner_registration_id", "owner_client_id") REFERENCES "client_registration"("id", "client_id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "sample"
  ADD CONSTRAINT "chk_sample_owner_registration_requires_client"
  CHECK ("owner_registration_id" IS NULL OR "owner_client_id" IS NOT NULL);

ALTER TABLE "sample"
  ADD CONSTRAINT "chk_sample_sold_sacks_non_negative"
  CHECK ("sold_sacks" >= 0);

ALTER TABLE "sample"
  ADD CONSTRAINT "chk_sample_lost_sacks_non_negative"
  CHECK ("lost_sacks" >= 0);

ALTER TABLE "sample"
  ADD CONSTRAINT "chk_sample_sold_lost_within_declared_sacks"
  CHECK (
    "declared_sacks" IS NULL
    OR
    ("sold_sacks" + "lost_sacks") <= "declared_sacks"
  );

CREATE INDEX "idx_client_status_code" ON "client"("status", "code");
CREATE INDEX "idx_client_created_id" ON "client"("created_at", "id");
CREATE INDEX "idx_client_registration_client_status_created"
  ON "client_registration"("client_id", "status", "created_at");
CREATE INDEX "idx_client_audit_target_created" ON "client_audit_event"("target_client_id", "created_at");
CREATE INDEX "idx_client_audit_registration_created" ON "client_audit_event"("target_registration_id", "created_at");
CREATE INDEX "idx_client_audit_actor_created" ON "client_audit_event"("actor_user_id", "created_at");
CREATE INDEX "idx_client_audit_event_type_created" ON "client_audit_event"("event_type", "created_at");
CREATE INDEX "idx_client_audit_created" ON "client_audit_event"("created_at");
CREATE INDEX "idx_sample_owner_client" ON "sample"("owner_client_id");
CREATE INDEX "idx_sample_owner_registration" ON "sample"("owner_registration_id");
CREATE INDEX "idx_sample_movement_sample_status_date_id"
  ON "sample_movement"("sample_id", "status", "movement_date", "id");
CREATE INDEX "idx_sample_movement_sample_type_status_date_id"
  ON "sample_movement"("sample_id", "movement_type", "status", "movement_date", "id");
CREATE INDEX "idx_sample_movement_buyer_type_status_date_id"
  ON "sample_movement"("buyer_client_id", "movement_type", "status", "movement_date", "id");

CREATE OR REPLACE FUNCTION reject_client_audit_event_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'client_audit_event is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reject_client_audit_event_update
BEFORE UPDATE ON "client_audit_event"
FOR EACH ROW
EXECUTE FUNCTION reject_client_audit_event_mutation();

CREATE TRIGGER trg_reject_client_audit_event_delete
BEFORE DELETE ON "client_audit_event"
FOR EACH ROW
EXECUTE FUNCTION reject_client_audit_event_mutation();
